# Generated by Django 4.2 on 2024-09-17 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_blog_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('can_published', 'Can published blog')], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
    ]
