# Generated by Django 5.1.1 on 2024-09-10 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_client_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MailingSettings',
            new_name='Mailing',
        ),
    ]
