# Generated by Django 4.2 on 2024-09-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_mailing_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='next_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время следующей рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время начала рассылки'),
        ),
    ]
