# Generated by Django 4.2 on 2024-09-17 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mailing_next_time_alter_mailing_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('set_inactive', 'Can block mailing')], 'verbose_name': 'Настройка рассылки', 'verbose_name_plural': 'Настройки рассылки'},
        ),
    ]
